### ISSUE TITLE
mux function could support a way to output its progress

### ISSUE THREAD

**Issue by rvbg** [GitBib/pymkv2#3]
**Is your enhancement request related to a problem? Please describe.**
When muxing something with mkvmerge it outputs the current progress in percent.
The current implementation of mux does not seem to support that information, which would be great to have, especially when running async or when muxing large files.

**Describe the solution you'd like**
Having an event function in the main object, which returns the progress, which is called when new progress information arrives.

Example:
```
mkv = MKVFile('/path/to/file.mkv')
mkv.remove_track(0)
mkv.mux('/path/to/output.mkv', gui.set_current_progress)
```
or
```
mkv = MKVFile('/path/to/file.mkv')
mkv.remove_track(0)
mkv.connect_event_new_progress(gui.set_current_progress)
mkv.mux('/path/to/output.mkv')
```

**Implementation steps**
 - [ ] Look at the output of mkvmerge and find a way to grab that information
 - [ ] Interpret that data
 - [ ] Add an event function which is called on new progress and returns that data
 - [ ] Add a variable to hold the connected function and a setter function to connect an external function to that event function

**Additional context**
I implemented something similar a few years ago, which still works, but the code is more a proof of concept, than a good implementation. It can be found [here](https://github.com/rvbg/mks-extractor-gui/blob/262c5c59f45af591165e17572b312dfe99253081/src/MKS%20Extractor%20GUI/Extractor.cs#L130).
That function is used in combination with a gui progress bar.

Let me know, if you want help implementing this and the enhancement request from yesterday.

**Comment by GitBib** [comment]
This is going to take more time. We need to figure out the best way to do it.

**Comment by rvbg** [comment]
Hi, I'm back to working on my project and will try to implement this. If I'm successful, I'll try to open a pull request.
But I've now come across another serious problem and will open a new issue for it.

**Comment by xMohnad** [comment]
You can handle progress like this:


```python
import re
import subprocess
import sys

cmd = [
    "mkvmerge",
    "-o",
    "output.mkv",
    "input1.mkv",
    "input2.mkv",
]

proc = subprocess.Popen(
    cmd,
    stdout=subprocess.PIPE,  
    stderr=subprocess.PIPE,
    text=True,
    bufsize=1,
)

def progress():
    progress_re = re.compile(r"(\d+)%")
    last_percent = -1
    if proc.stderr:
        for line in proc.stderr:
            if "Error:" in line or "error" in line.lower():
                yield line.strip(), None
            elif match := progress_re.search(line):
                percent = int(match.group(1))
                if percent != last_percent:
                    yield None, percent
                    last_percent = percent

for err, percent in progress():
    if err:
        sys.stderr.write(f"\n{err}\n")
    elif percent is not None:
        sys.stdout.write(f"\r{percent}%")
        sys.stdout.flush()

code = proc.wait()
print(f"\nExit code: {code}")
```

This way, the caller can simply iterate over the generator and get the current percentage updates.
It should be straightforward to adapt this into an internal event system.
